[package]
name = "ircbot_backend"
version = "1.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1", features = ["derive"] }
reqwest = "0.11"
dotenv = "0.15.0"
serde_json = "1.0"
lazy_static = "1.4.0"

